
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 06 19:50:57 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PP = 30;
  public static final int MM = 31;
  public static final int LOGAND = 27;
  public static final int CHAR = 45;
  public static final int CONST = 15;
  public static final int LPAREN = 35;
  public static final int SEMI = 32;
  public static final int CONTINUE = 14;
  public static final int LOGNEQU = 22;
  public static final int RPAREN = 36;
  public static final int BOOL = 44;
  public static final int COMMA = 33;
  public static final int LOGGR = 23;
  public static final int CLASS = 4;
  public static final int LOGLWEQU = 26;
  public static final int DIV = 19;
  public static final int LOGEQU = 21;
  public static final int IF = 5;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 29;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int ADD = 16;
  public static final int NUMBER = 42;
  public static final int MOD = 20;
  public static final int IDENT = 43;
  public static final int BREAK = 3;
  public static final int VOID = 10;
  public static final int LOGLW = 25;
  public static final int LOGGREQU = 24;
  public static final int ELSE = 41;
  public static final int LBRACE = 39;
  public static final int RBBRACE = 38;
  public static final int LBBRACE = 37;
  public static final int READ = 8;
  public static final int WHILE = 12;
  public static final int LOGOR = 28;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int SUB = 17;
  public static final int PRINT = 7;
  public static final int DO = 11;
}

